/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package gui;

import dbcon.DBConnect;
import dbcon.SQLHelper;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import user_accounts.User;

/**
 *
 * @author hnaro
 */
public class CreateCustomer extends javax.swing.JFrame {
    
    private User user;
    DBConnect conn;
    SQLHelper sqlhelper;
    
    /**
     * Creates new form CreateCustomer
     */
    public CreateCustomer(User user) throws SQLException{
        this.user = user;
        
        initComponents();
        setTitle("Add Customer | GARITS");
        setVisible(true);
        
        conn = new DBConnect();
        if (conn == null) {
            JOptionPane.showMessageDialog(this, "DB connection failed.", "Error", JOptionPane.ERROR_MESSAGE);
        } else {
            sqlhelper = new SQLHelper(conn.open());
        }
        
        jPanelAccHolder.setVisible(false);
    }
    
    /**
     * Text fields validations
     */
    private boolean validateFields() {
        boolean validated = false;
        String EMAIL_PATTERN = "^(.+)@(.+)$";
        
        // check for empty fields
        if (tffirstname.getText().isEmpty() || tflastname.getText().isEmpty() || 
                tfaddress.getText().isEmpty() || tfpostcode.getText().isEmpty()
                || tfemail.getText().isEmpty() || tfphoneno.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Please fill in all the boxes", "Error", JOptionPane.ERROR_MESSAGE);
        }
        // email pattern from https://howtodoinjava.com/java/regex/java-regex-validate-email-address/
        else if (!tfemail.getText().matches(EMAIL_PATTERN)){
            JOptionPane.showMessageDialog(this, "Please enter a valid email", "Error", JOptionPane.ERROR_MESSAGE);
        }
        // validating telephone number, must be 11 digits
        else if(!tfphoneno.getText().matches("\\d{8}|\\d{11}")) {
            JOptionPane.showMessageDialog(this, "Please enter a valid telephone number", "Error", JOptionPane.ERROR_MESSAGE);
        } else {
            validated = true;
        }
        return validated;
    }
    
    /*
     * Clears all fields
     * @param 
     */
    private void clearAllFields() {
        tffirstname.setText(null);
        tflastname.setText(null);
        tfaddress.setText(null);
        tfpostcode.setText(null);
        tfphoneno.setText(null);
        tfemail.setText(null);
        cbaccountholder.setSelected(false);
        cbpaylater.setSelected(false);
        cbdiscount.setSelectedIndex(-1);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btback = new javax.swing.JButton();
        lbltitle = new javax.swing.JLabel();
        lblname = new javax.swing.JLabel();
        lbladdress = new javax.swing.JLabel();
        lblpostcode = new javax.swing.JLabel();
        lblphoneno = new javax.swing.JLabel();
        lblemail = new javax.swing.JLabel();
        tffirstname = new javax.swing.JTextField();
        tfaddress = new javax.swing.JTextField();
        tfpostcode = new javax.swing.JTextField();
        tfphoneno = new javax.swing.JTextField();
        tfemail = new javax.swing.JTextField();
        btadd = new javax.swing.JButton();
        lbllastname = new javax.swing.JLabel();
        tflastname = new javax.swing.JTextField();
        cbaccountholder = new javax.swing.JCheckBox();
        jPanelAccHolder = new javax.swing.JPanel();
        cbpaylater = new javax.swing.JCheckBox();
        jLabel1 = new javax.swing.JLabel();
        cbdiscount = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        btback.setText("Back");
        btback.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btbackActionPerformed(evt);
            }
        });

        lbltitle.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lbltitle.setText("Add Customer");

        lblname.setText("First Name: ");

        lbladdress.setText("Address: ");

        lblpostcode.setText("Postcode: ");

        lblphoneno.setText("Phone Number: ");

        lblemail.setText("Email: ");

        tfphoneno.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tfphonenoKeyTyped(evt);
            }
        });

        btadd.setText("Add");
        btadd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btaddActionPerformed(evt);
            }
        });

        lbllastname.setText("Last Name: ");

        cbaccountholder.setText("Account Holder");
        cbaccountholder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbaccountholderActionPerformed(evt);
            }
        });

        cbpaylater.setText("Pay Later");

        jLabel1.setText("Discount Plan: ");

        cbdiscount.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Fixed", "Variable", "Flexible" }));
        cbdiscount.setSelectedIndex(-1);

        javax.swing.GroupLayout jPanelAccHolderLayout = new javax.swing.GroupLayout(jPanelAccHolder);
        jPanelAccHolder.setLayout(jPanelAccHolderLayout);
        jPanelAccHolderLayout.setHorizontalGroup(
            jPanelAccHolderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelAccHolderLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelAccHolderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cbpaylater)
                    .addGroup(jPanelAccHolderLayout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(cbdiscount, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(26, Short.MAX_VALUE))
        );
        jPanelAccHolderLayout.setVerticalGroup(
            jPanelAccHolderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelAccHolderLayout.createSequentialGroup()
                .addComponent(cbpaylater)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelAccHolderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(cbdiscount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(btback)
                .addGap(50, 50, 50)
                .addComponent(lbltitle)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(74, 74, 74)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(cbaccountholder)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(btadd, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jPanelAccHolder, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblemail)
                                    .addComponent(lbladdress)
                                    .addComponent(lbllastname)
                                    .addComponent(lblname)
                                    .addComponent(lblphoneno)
                                    .addComponent(lblpostcode))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(tffirstname, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE)
                                    .addComponent(tfaddress, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(tfpostcode, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(tfphoneno, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(tfemail, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(tflastname, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(75, 75, 75))))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {tfaddress, tfemail, tffirstname, tfphoneno, tfpostcode});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btback)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lbltitle)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tffirstname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblname))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tflastname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbllastname))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfaddress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbladdress))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfpostcode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblpostcode))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfphoneno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblphoneno))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfemail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblemail))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cbaccountholder)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanelAccHolder, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btadd)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btbackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btbackActionPerformed
        dispose();
        try {
            conn.close();
        } catch (SQLException ex) {
            System.err.println(ex.getMessage());
        }
        new MainMenu(user);
    }//GEN-LAST:event_btbackActionPerformed

    private void btaddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btaddActionPerformed
        String lastID = "";
        if (validateFields() == true) {
            int accHolder = (boolean) cbaccountholder.isSelected() ? 1 : 0;
            // add customer to database
            try {
                String sql = ("INSERT INTO Customer (fname, lname, address, postcode, "
                            + "telephone, email, accountHolder) "
                            + "VALUES ('" + tffirstname.getText() + "', "
                            + "'" + tflastname.getText() + "', "
                            + "'" + tfaddress.getText() + "', "
                            + "'" + tfpostcode.getText() + "', "
                            + "'" + tfphoneno.getText() + "', "
                            + "'" + tfemail.getText() + "', "
                            + "'" + accHolder + "')");
                PreparedStatement ps = sqlhelper.getConnection().prepareStatement(sql, Statement.RETURN_GENERATED_KEYS);
                ps.executeUpdate();
                ResultSet rs = ps.getGeneratedKeys();
                if(rs.next()) {
                    lastID = rs.getString(1);
                }
            } catch (SQLException e) {
                e.printStackTrace();
            }
            
            int paylater = (boolean) cbpaylater.isSelected() ? 1 : 0;
            // if account holder
            if (cbaccountholder.isSelected()) {
                try {
                    String sql = ("INSERT INTO Customer_Account (CustomerID, payLater, discountType )"
                            + "VALUES ('" + lastID + "', "
                            + "'" + paylater + "', "
                            + "'" + cbdiscount.getSelectedItem() + "')");
                    sqlhelper.updateTable(sql);
                } catch (SQLException e) {
                    e.printStackTrace();
                }
            }
            JOptionPane.showMessageDialog(this, "New customer created");
            clearAllFields();
            jPanelAccHolder.setVisible(false);
        }
    }//GEN-LAST:event_btaddActionPerformed

    private void tfphonenoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfphonenoKeyTyped
        // only numberic input allowed
        char c = evt.getKeyChar();
        if (((c < '0') || (c > '9')) && (c != evt.VK_BACK_SPACE)) {
            evt.consume();
        }
    }//GEN-LAST:event_tfphonenoKeyTyped

    private void cbaccountholderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbaccountholderActionPerformed
        if(cbaccountholder.isSelected()) {
             jPanelAccHolder.setVisible(true);
        } else {
            jPanelAccHolder.setVisible(false);
        }
    }//GEN-LAST:event_cbaccountholderActionPerformed
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btadd;
    private javax.swing.JButton btback;
    private javax.swing.JCheckBox cbaccountholder;
    private javax.swing.JComboBox<String> cbdiscount;
    private javax.swing.JCheckBox cbpaylater;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanelAccHolder;
    private javax.swing.JLabel lbladdress;
    private javax.swing.JLabel lblemail;
    private javax.swing.JLabel lbllastname;
    private javax.swing.JLabel lblname;
    private javax.swing.JLabel lblphoneno;
    private javax.swing.JLabel lblpostcode;
    private javax.swing.JLabel lbltitle;
    private javax.swing.JTextField tfaddress;
    private javax.swing.JTextField tfemail;
    private javax.swing.JTextField tffirstname;
    private javax.swing.JTextField tflastname;
    private javax.swing.JTextField tfphoneno;
    private javax.swing.JTextField tfpostcode;
    // End of variables declaration//GEN-END:variables
}
