/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package gui;

import java.awt.CardLayout;
import javax.swing.*;
import java.sql.*;

import dbcon.DBConnect;
import dbcon.SQLHelper;
import user_accounts.User;

/**
 *
 * @author hnaro
 */
public class MainMenu extends javax.swing.JFrame{

    DBConnect conn = new DBConnect();
    Connection con;
    JFrame frame;

    {
        try {
            con =  conn.open();
        } catch (SQLException e) {
            e.printStackTrace();
        }
    }

    DefaultListModel listmodel = new DefaultListModel();
    User user;
    
    /**
     * Creates new MainMenu form/page.
     * @param user
    */
    public MainMenu(User user) {
        this.user = user;
        initComponents();
        setTitle("Mainmenu | GARITS");
        setVisible(true);
        // privilege
        // if the user is admin, admin menu set to enable and other to disable
        if (user.getRole().equalsIgnoreCase("Administrator")) {
            btadminmenu.setEnabled(true);
            btpartsmenu.setEnabled(false);
            btjobsmenu.setEnabled(false);
            btcustomermenu.setEnabled(false);
        }
        // user is mechanic
        if (user.getRole().equalsIgnoreCase("Mechanic")) {
            btadminmenu.setEnabled(false);
            btpartsmenu.setEnabled(true);
            btjobsmenu.setEnabled(true);
            btcustomermenu.setEnabled(false);
        }
        populateAdmin(user);
    }
    
    /**
     * populate MainMenu form
     * @param user
     */
    private void populateAdmin(User user) {
        this.lbluserid.setText(user.getUsername());
        
        // making the menu list to single selection
        jListItem.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
    }
    /*
    private void populateParts(User user){
        this.lbluserid.setText(user.getUsername());
        jListadmin.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
        partsListModel.clear();
        partsListModel.addElement("View Orders");
        partsListModel.addElement("Create Order");
        jListadmin.setModel(partsListModel);
        partsPanel.add(jListadmin);
    }*/

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainPanel = new javax.swing.JPanel();
        jListItem = new javax.swing.JList<>();
        btpartsmenu = new javax.swing.JButton();
        btjobsmenu = new javax.swing.JButton();
        btcustomermenu = new javax.swing.JButton();
        btlogout = new javax.swing.JButton();
        btview = new javax.swing.JButton();
        lbluserid = new javax.swing.JLabel();
        btadminmenu = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(900, 500));
        setResizable(false);
        setSize(new java.awt.Dimension(0, 0));

        mainPanel.setBackground(new java.awt.Color(204, 204, 204));
        mainPanel.setPreferredSize(new java.awt.Dimension(0, 370));

        javax.swing.GroupLayout mainPanelLayout = new javax.swing.GroupLayout(mainPanel);
        mainPanel.setLayout(mainPanelLayout);
        mainPanelLayout.setHorizontalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jListItem, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        mainPanelLayout.setVerticalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainPanelLayout.createSequentialGroup()
                .addComponent(jListItem, javax.swing.GroupLayout.DEFAULT_SIZE, 370, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );

        btpartsmenu.setText("Parts Menu");
        btpartsmenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btpartsmenuActionPerformed(evt);
            }
        });

        btjobsmenu.setText("Jobs Menu");
        btjobsmenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btjobsmenuActionPerformed(evt);
            }
        });

        btcustomermenu.setText("Customers Menu");
        btcustomermenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btcustomermenuActionPerformed(evt);
            }
        });

        btlogout.setText("Logout");
        btlogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btlogoutActionPerformed(evt);
            }
        });

        btview.setText("View");
        btview.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btviewActionPerformed(evt);
            }
        });

        lbluserid.setText("UserID");

        btadminmenu.setText("Admin Menu");
        btadminmenu.setEnabled(false);
        btadminmenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btadminmenuActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 839, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addComponent(btpartsmenu, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50)
                .addComponent(btjobsmenu, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50)
                .addComponent(btcustomermenu)
                .addGap(50, 50, 50)
                .addComponent(btadminmenu, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50)
                .addComponent(btlogout))
            .addComponent(lbluserid)
            .addComponent(btview, javax.swing.GroupLayout.DEFAULT_SIZE, 839, Short.MAX_VALUE)
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btadminmenu, btcustomermenu, btjobsmenu, btlogout, btpartsmenu});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btjobsmenu)
                    .addComponent(btlogout)
                    .addComponent(btpartsmenu)
                    .addComponent(btcustomermenu)
                    .addComponent(btadminmenu))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(mainPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btview)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbluserid))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btpartsmenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btpartsmenuActionPerformed

        listmodel.clear();
        if  (listmodel.size() == 0) {
            // parts menu options
            listmodel.addElement("Create Order");
            listmodel.addElement("View Orders");
            listmodel.addElement("View Spare Parts");
            jListItem.setModel(listmodel);
        }                    
    }//GEN-LAST:event_btpartsmenuActionPerformed

    private void btjobsmenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btjobsmenuActionPerformed
        listmodel.clear();
        if  (listmodel.size() == 0) {
            // jobs menu options
            listmodel.addElement("");
            jListItem.setModel(listmodel);
        }                   
    }//GEN-LAST:event_btjobsmenuActionPerformed

    private void btcustomermenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btcustomermenuActionPerformed
        listmodel.clear();
        // customer menu options
        if  (listmodel.size() == 0) {
            listmodel.addElement("Add Customer");
            listmodel.addElement("Edit/Delete Customer");
            listmodel.addElement("Add Vehicle");
            jListItem.setModel(listmodel);
        }
    }//GEN-LAST:event_btcustomermenuActionPerformed

    private void btviewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btviewActionPerformed
        String selectedItem = jListItem.getSelectedValue();
        System.out.println(selectedItem);
        try{
            switch(selectedItem){
                case "Add User" -> {
                    dispose();
                    new AddUser(user);
                }
                case "Edit/Delete User" -> {
                    dispose();
                    new EditDeleteUser(user);
                }

                case "Backup/Restore Database" -> {
                    dispose();
                    new BackupRestoreDB(user);
                }

                case "Add Customer" -> {
                    dispose();
                    new CreateCustomer(user);
                }
                
                case "Edit/Delete Customer" -> {
                    dispose();
                    new EditDeleteCustomer(user);
                }
                
                case "Add Vehicle" -> {
                    dispose();
                    new Vehicle(user);
                }

                case "View Orders" -> {
                    this.setVisible(false);
                    frame = new JFrame("Order");
                    frame.setContentPane(new viewOrders(con, this, frame).orderView);
                    frame.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
                    frame.pack();
                    frame.setVisible(true);
                }

                case "Create Order" -> {
                    this.setVisible(false);
                    frame = new JFrame("Order");
                    frame.setContentPane(new orderForm(con, this, frame).formView);
                    frame.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
                    frame.pack();
                    frame.setVisible(true);
                }

                case "View Spare Parts" -> {
                    this.setVisible(false);
                    frame = new JFrame("Order");
                    frame.setContentPane(new viewSpareParts(con, this, frame).sparePanel);
                    frame.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
                    frame.pack();
                    frame.setVisible(true);
                }
            }
        } catch (SQLException ex){
            ex.printStackTrace();
        }

    }//GEN-LAST:event_btviewActionPerformed

    private void btlogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btlogoutActionPerformed
        dispose();
        try{

            new Login();
        } catch (SQLException ex){
            ex.printStackTrace();
        }
    }//GEN-LAST:event_btlogoutActionPerformed

    private void btadminmenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btadminmenuActionPerformed
        listmodel.clear();
        if  (listmodel.size() == 0) {
            // admin menu options
            listmodel.addElement("Add User");
            listmodel.addElement("Edit/Delete User");
            listmodel.addElement("Backup/Restore Database");
            jListItem.setModel(listmodel);
        }  
    }//GEN-LAST:event_btadminmenuActionPerformed


    private DefaultListModel<String> partsListModel = new DefaultListModel<>();

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btadminmenu;
    private javax.swing.JButton btcustomermenu;
    private javax.swing.JButton btjobsmenu;
    private javax.swing.JButton btlogout;
    private javax.swing.JButton btpartsmenu;
    private javax.swing.JButton btview;
    private javax.swing.JList<String> jListItem;
    private javax.swing.JLabel lbluserid;
    private javax.swing.JPanel mainPanel;
    // End of variables declaration//GEN-END:variables

}
